locale                   : "en"
title                    : "Sono Mayrit"
author: "SM"
description: ""
url: "http://sonomayrit.xyz"
baseurl: ""
lang: "es"

excerpt_separator: <!--more-->
plugins: [jekyll-paginate]

markdown: kramdown
kramdown:
  header_offset: 1

permalink: /:year/:month/:day/:title/
paginate_pathds: /:num/
paginate: 5

collections:
  press:
    sort_by: date
    output: true
  donations:
    sort_by: year
    output: true

exclude:
 - package-lock.json
 - package.json
 - postcss.config.js
 - tailwind.config.js
 - .nova
 

future: true

collections:
  projects:
    output: true



picture:
  source: "src/Images"
  output: "src/Images/generated"
  suppress_warnings: true